remove prom rules from openshift monitoring namespace
stolostron/multicluster-observability-operator pull request #1256
Opened 2023-10-16 08:10 UTC by coleenquadros

2023-10-16 08:51 UTC, coleenquadros commented
/retest-required

2023-10-16 09:32 UTC, coleenquadros commented
Verification 
```
coquadro@coquadro-mac prometheus-2.47.1.darwin-arm64 % oc get prometheusrules -n open-cluster-management-observability
NAME                            AGE
acm-observability-alert-rules   20m
coquadro@coquadro-mac prometheus-2.47.1.darwin-arm64 % oc get prometheusrules -n openshift-monitoring                 
NAME                                           AGE
alertmanager-main-rules                        18d
cluster-monitoring-operator-prometheus-rules   18d
kube-state-metrics-rules                       18d
kubernetes-monitoring-rules                    18d
node-exporter-rules                            18d
prometheus-k8s-prometheus-rules                18d
prometheus-k8s-thanos-sidecar-rules            18d
prometheus-operator-rules                      18d
telemetry                                      18d
thanos-querier                                 18d
coquadro@coquadro-mac prometheus-2.47.1.darwin-arm64 % 

```

2023-10-16 14:19 UTC, saswatamcode commented
/retest

2023-10-17 09:47 UTC, coleenquadros commented
/test test-e2e

2023-10-18 15:04 UTC, coleenquadros commented
/test test-unit

2023-10-18 16:13 UTC, subbarao-meduri requested changes

2023-10-19 01:53 UTC, subbarao-meduri approved these changes
/lgtm

2023-10-19 01:56 UTC, merged