Update mco
stolostron/multicluster-observability-operator pull request #1483
Opened 2024-06-12 13:21 UTC by coleenquadros

2024-06-12 16:25 UTC, douglascamata requested changes

2024-06-12 16:25 UTC, douglascamata commented on operators/multiclusterobservability/controllers/placementrule/manifestwork.go
> +		log.Info("Coleen in local-cluster", "cluster", clusterName, "namespace", clusterNamespace)
accidental debug log left behind here 👀

2024-06-13 12:32 UTC, thibaultmg approved these changes
/lgtm

2024-06-14 06:55 UTC, saswatamcode approved these changes
/lgtm

2024-06-14 08:52 UTC, philipgough approved these changes

2024-06-14 11:54 UTC, merged